apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-gateway
  template:
    metadata:
      labels:
        app: cloud-gateway
    spec:
      containers:
        - name: cloud-gateway
          image: IMAGE_URL
          imagePullPolicy: Always
          ports:
            - containerPort: 9090

---

apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway-service
spec:
  selector:
    app: cloud-gateway
  ports:
    - port: 80
      targetPort: 9090
  type: LoadBalancer